### ISSUE TITLE
Document new options in v1.1.0

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckanext-grouphierarchy-sddi#12]
We need some documentation for the new options. A possible location is the README.md in this repo.

**Comment by BWibo** [comment]
@MarijaKnezevic @TomeCirun:

We need a documentation for the new options. A brief rework the README.md shoud do. For now, it would be sufficient to list the new config options for `ckan.ini`, their default values and how they can be used (URL/local path/...).

**Comment by MarijaKnezevic** [comment]
@BWibo this is on my "to-do" list for today and tomorrow.
Tome is working on the following [issue](https://github.com/tum-gis/ckanext-relation-sddi/issues/6) and I am working on the documentation.

**Comment by MarijaKnezevic** [comment]
The new options are described in `README.md`. The `CHANGELOG.md` file is created and updated for previous releases.
