### ISSUE TITLE
Clarification documentation new options

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckanext-grouphierarchy-sddi#13]
The description of the new options is unclear/incomplete:
  * It is not clear, weather it is possible to use a local path or just an URL for `ckan.backgorund_image`.

**Comment by BWibo** [comment]
A screenshot showning where `introParagrah` and `introText` are located would be helpful too.

**Comment by BWibo** [comment]
And it should be more clear, what the default configuration for each option is.

**Comment by MarijaKnezevic** [comment]
I added a few screenshots and a description for [personalisation](https://github.com/tum-gis/ckanext-grouphierarchy-sddi#personalisation).
The information about `init_data.json` I will add accordingly the issue #14

**Comment by BWibo** [comment]
Closing this, discussions continues in #14.
