### ISSUE TITLE
Missing option for `init_data.json`

### ISSUE THREAD

**Issue by BWibo** [tum-gis/ckanext-grouphierarchy-sddi#14]
Where is the configuration option for: `https://github.com/tum-gis/ckanext-grouphierarchy-sddi/blob/main/ckanext/grouphierarchy/init_data.json`?
It needs to be possible to configure this, when a new instance is created, see description tum-gis/ckan-docker#23.
The option should support both:
- Provide a JSON file in the Docker container and specify it with a local path
- An external URL to a JSON file

Is this already implemented and just the documentation is missing, or is it not there jet?

**Comment by BWibo** [comment]
@MarijaKnezevic An extension of the documentation is requried here too. There should be a description + example of how `init_data.json` files have to be structured.

**Comment by TomeCirun** [comment]
It's already implemented we just need to document it @BWibo @MarijaKnezevic

**Comment by BWibo** [comment]
Thx @MarijaKnezevic, @TomeCirun. However, there are still some points unclear and undocumented. This applies both for the implementation and documentation. Following issues need clarification:

- What is the default setting of the variable (and the others too!)? This needs to be explicitly specified in the docs.
- Can only a local path and/or an URL be used as values for `ckan.grouphierarchy.init_data`? Are there any limitations, if a local path is specified (e.g. inside the extension dir)? What file permissions have to be used in that case?

- The example of `init_data.json` is hard to read. Also for the description it is impossible to understand the structure. I suggest to create a minimal example that is well formatted and fits on the screen without having to scroll. Additionally, it should be explained what options you have with that file. Can we e.g. leave out organisations, if I don't want to specify them? What is required content, what is optional?
  
  ![grafik](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/assets/7643434/5643457c-cf15-40e5-aade-0810642db4d9)

- When is `init_data.json` loaded? Only at first initialization of a fresh instance, or at every startup? How is overwriting of e.g. existing groups handeled, if e.g. then content `init_data.json` changes? Is e.g. a changed image path replaced. This needs to be documented too. Please also add to the docs where images should be stored and what permissions the files need, that the CKAN webserver can view them. Are external image URLs possible too (CORS?)?

**Comment by BWibo** [comment]
@MarijaKnezevic @TomeCirun Any news on this?

**Comment by MarijaKnezevic** [comment]
@BWibo 
I've updated the [README.md](https://github.com/tum-gis/ckanext-grouphierarchy-sddi/blob/main/README.md) file last week. 

Regarding your third point about example of the data structure:
I have added an example that is easier to read. I also left this example because it nicely shows how it is possible to add a child-parent structure.

**Comment by BWibo** [comment]
I made some edits in #16. Please check if that's correct.

**Comment by MarijaKnezevic** [comment]
Yes, they are fine. Thanks. I will close this issue and merge PR
